language: node_js
node_js:
  - 0.10

branches:
  only:
    - master

env:
  global:
    - secure: ckul1NeOfQi13LxMvppoXzc/O08YEf2HqDbyE3dl2mgnjQVfB8ASRKSyvp6jZhKYEPX+WUwfdpHid8fGq3ESwTAUT41QF+HBUr7xdz6772m7Qm0nMJ94FaT7iL+2sR2O6WmqpWWktUSOkN4omI7xOv9b1MVHYiYPct965SM3SdI=
    - secure: gJlW/YbFeC7HAiFxH+M4Ia8BYP0n4PvLRT2bG5YgfFsRfF7yNkppCIt/cSxrl5SUhsT6UnArLVejP1nw6U6Pxu4KoOKdnWLnFjU2/qtU0IpEZDgex4u1wthxe37qd/fkNRq5U243c4N9UuY8YLJm0rDVYhxVsP1QQSymWThhis4=

before_install:
  # Add DataStax apt repo for Cassandra
  - curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
  - echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/dsc.sources.list

  # Add PPA repos for miscellaneous dependencies
  - echo 'yes' | sudo add-apt-repository ppa:oae/deps
  - echo 'yes' | sudo add-apt-repository ppa:coolwanglu/pdf2htmlex
  - sudo apt-get update

  # Install cassandra 2.0.8 manually
  - sudo service cassandra stop
  - sudo apt-get install -y -o Dpkg::Options::=--force-confnew cassandra=2.0.8
  - sudo service cassandra start
  - sudo service cassandra status

  # Install nginx
  - sudo apt-get install nginx

  # Turn off unneeded services to free some memory
  - sudo service mysql stop
  - sudo service memcached stop
  - sudo service postgresql stop

  # Install Hilary deps
  - sudo apt-get install -qq graphicsmagick libreoffice pdftk chrpath pdf2htmlex
  - npm install -g grunt-cli

  # avocet-ui dependencies
  - npm install -g casperjs

  # Show the CasperJS and PhantomJS version for debugging purposes
  - casperjs --version
  - phantomjs --version

  # Install Hilary
  - cd ~/build/CUL-DigitalServices
  - git clone  --branch master --depth=1 git://github.com/CUL-DigitalServices/avocet-hilary.git ./avocet-hilary
  - cd ./avocet-hilary
  - npm install --production
  - node app.js | node_modules/.bin/bunyan -l error &

  # Configure avocet-ui / nginx
  - cd ~/build/CUL-DigitalServices/avocet-ui
  - npm install
  - "echo '{\"NGINX_USER\": \"root\",\"NGINX_GROUP\": \"root\",\"NGINX_HOSTNAME\": \"admin.oae.com\",\"UX_HOME\": \"/home/travis/build/CUL-DigitalServices/avocet-ui\",\"LOCAL_FILE_STORAGE_DIRECTORY\": \"/home/travis/build/CUL-DigitalServices/files\"}' > nginx/nginx.json"
  - grunt configNginx
  - sudo cp ./target/optimized/nginx/nginx.conf /etc/nginx/nginx.conf
  - sudo mkdir /usr/share/nginx/logs
  - sudo service nginx start

  # Wait for Hilary to have started up to start the tests in "script" phase
  - ./tools/travis/checkHilaryStart.sh

addons:
  hosts:
    - test.oae.com
    - admin.oae.com

script:
  - grunt test --qunit-host test.oae.com

services:
  - elasticsearch
  - rabbitmq
  - redis-server

after_success:
  # Package and upload to Amazon S3
  - etc/scripts/travis-upload.sh

notifications:
  irc: "irc.freenode.org#ucam-ds-oa"
